export const pokeMart = [
    {
        id: 0,
        name: 'Poke Ball',
        type: 'Ball',
        price: 50,
        stock: 100,
        inCart: 0,
        icon: '',
    },
    {
        id: 1,
        name: 'Great Ball',
        type: 'Ball',
        price: 100,
        stock: 100,
        inCart: 0,
        icon: '',
    },
    {
        id: 2,
        name: 'Super Ball',
        type: 'Ball',
        price: 150,
        stock: 100,
        inCart: 0,
        icon: '',
    },
    {
        id: 3,
        name: 'Ultra Ball',
        type: 'Ball',
        price: 200,
        stock: 100,
        inCart: 0,
        icon: '',
    },
    {
        id: 7,
        name: 'Sweet Pokeblock',
        type: 'Pokeblock',
        price: 100,
        stock: 100,
        inCart: 0,
        icon: '',
    },
    {
        id: 8,
        name: 'Sour Pokeblock',
        type: 'Pokeblock',
        price: 100,
        stock: 100,
        inCart: 0,
        icon: '',
    },
    {
        id: 9,
        name: 'Spicy Pokeblock',
        type: 'Pokeblock',
        price: 100,
        stock: 100,
        inCart: 0,
        icon: '',
    }
]

export default pokeMart;